### ISSUE TITLE
Объединить критерии Б16 и Д3 в один базовый критерий

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/intensive-javascript-criteria#32]
> Б16. Для итерирования по массивам и структурам данных по которому можно итерироваться (Iterable) используется конструкция for .. of
> Д25. Для работы с JS-коллекциями используются итераторы для массивов

Евгений Воронин [24 minutes ago] 
Я бы улучшил так:
1) Пробуем перебирать при помощи forEach, map, reduce, если что-то не так, то...
2) Пробуем перебирать при помощи `for ... of`, если что-то не так, то...
3) Если по каким-то причинам не подходит, делаем `Array.from`

**Comment by SashaKa** [comment]
@o0 , делаем?

**Comment by o0** [comment]
@SashaKa это про JS уровень 2, а не уровень 1.

**Comment by zeckson** [comment]
перенёс https://github.com/htmlacademy/intensive-ecmascript-criteria/issues/9

**Comment by zeckson** [comment]
Что вы тут за `milestone`ы устроили?
